UPDATE products SET product_name='Dell Inspiron 15', category='Electronics', unit_price=836 WHERE product_id=1;
UPDATE products SET product_name='HP Pavilion 14', category='Electronics', unit_price=1173 WHERE product_id=2;
UPDATE products SET product_name='Lenovo ThinkPad E14', category='Electronics', unit_price=1510 WHERE product_id=3;
UPDATE products SET product_name='Apple MacBook Air', category='Electronics', unit_price=1847 WHERE product_id=4;
UPDATE products SET product_name='Acer Aspire 7', category='Electronics', unit_price=2184 WHERE product_id=5;
UPDATE products SET product_name='Asus VivoBook', category='Electronics', unit_price=2521 WHERE product_id=6;
UPDATE products SET product_name='Samsung 24-inch Monitor', category='Electronics', unit_price=2858 WHERE product_id=7;
UPDATE products SET product_name='LG UltraWide Monitor', category='Electronics', unit_price=3195 WHERE product_id=8;
UPDATE products SET product_name='Logitech Wireless Mouse', category='Electronics', unit_price=3532 WHERE product_id=9;
UPDATE products SET product_name='HP Wireless Keyboard', category='Electronics', unit_price=3869 WHERE product_id=10;
UPDATE products SET product_name='Sony Bluetooth Speaker', category='Electronics', unit_price=4206 WHERE product_id=11;
UPDATE products SET product_name='JBL Flip Speaker', category='Electronics', unit_price=4543 WHERE product_id=12;
UPDATE products SET product_name='Canon EOS Camera', category='Electronics', unit_price=4880 WHERE product_id=13;
UPDATE products SET product_name='Nikon DSLR Camera', category='Electronics', unit_price=5217 WHERE product_id=14;
UPDATE products SET product_name='SanDisk SSD', category='Electronics', unit_price=5554 WHERE product_id=15;
UPDATE products SET product_name='WD External HDD', category='Electronics', unit_price=5891 WHERE product_id=16;
UPDATE products SET product_name='TP-Link Router', category='Electronics', unit_price=6228 WHERE product_id=17;
UPDATE products SET product_name='Mi Power Bank', category='Electronics', unit_price=6565 WHERE product_id=18;
UPDATE products SET product_name='Apple Magic Keyboard', category='Electronics', unit_price=6902 WHERE product_id=19;
UPDATE products SET product_name='Epson Printer', category='Electronics', unit_price=7239 WHERE product_id=20;
UPDATE products SET product_name='Office Chair', category='Furniture', unit_price=7576 WHERE product_id=21;
UPDATE products SET product_name='Study Desk', category='Furniture', unit_price=7913 WHERE product_id=22;
UPDATE products SET product_name='Bookshelf', category='Furniture', unit_price=8250 WHERE product_id=23;
UPDATE products SET product_name='Wooden Cabinet', category='Furniture', unit_price=8587 WHERE product_id=24;
UPDATE products SET product_name='Dining Table', category='Furniture', unit_price=8924 WHERE product_id=25;
UPDATE products SET product_name='Coffee Table', category='Furniture', unit_price=9261 WHERE product_id=26;
UPDATE products SET product_name='TV Unit', category='Furniture', unit_price=9598 WHERE product_id=27;
UPDATE products SET product_name='Wardrobe', category='Furniture', unit_price=9935 WHERE product_id=28;
UPDATE products SET product_name='Sofa Set', category='Furniture', unit_price=10272 WHERE product_id=29;
UPDATE products SET product_name='Bed Frame', category='Furniture', unit_price=10609 WHERE product_id=30;
UPDATE products SET product_name='Nike T-Shirt', category='Clothing', unit_price=10946 WHERE product_id=31;
UPDATE products SET product_name='Adidas Hoodie', category='Clothing', unit_price=11283 WHERE product_id=32;
UPDATE products SET product_name='Levis Jeans', category='Clothing', unit_price=11620 WHERE product_id=33;
UPDATE products SET product_name='Puma Shorts', category='Clothing', unit_price=11957 WHERE product_id=34;
UPDATE products SET product_name='Formal Shirt', category='Clothing', unit_price=12294 WHERE product_id=35;
UPDATE products SET product_name='Casual Shirt', category='Clothing', unit_price=12631 WHERE product_id=36;
UPDATE products SET product_name='Jacket', category='Clothing', unit_price=12968 WHERE product_id=37;
UPDATE products SET product_name='Sweatshirt', category='Clothing', unit_price=13305 WHERE product_id=38;
UPDATE products SET product_name='Track Pants', category='Clothing', unit_price=13642 WHERE product_id=39;
UPDATE products SET product_name='Kurti', category='Clothing', unit_price=13979 WHERE product_id=40;
UPDATE products SET product_name='Atomic Habits', category='Books', unit_price=14316 WHERE product_id=41;
UPDATE products SET product_name='The Alchemist', category='Books', unit_price=14653 WHERE product_id=42;
UPDATE products SET product_name='Rich Dad Poor Dad', category='Books', unit_price=14990 WHERE product_id=43;
UPDATE products SET product_name='Deep Work', category='Books', unit_price=15327 WHERE product_id=44;
UPDATE products SET product_name='Clean Code', category='Books', unit_price=15664 WHERE product_id=45;
UPDATE products SET product_name='Python Crash Course', category='Books', unit_price=16001 WHERE product_id=46;
UPDATE products SET product_name='Ikigai', category='Books', unit_price=16338 WHERE product_id=47;
UPDATE products SET product_name='Sapiens', category='Books', unit_price=16675 WHERE product_id=48;
UPDATE products SET product_name='Zero to One', category='Books', unit_price=17012 WHERE product_id=49;
UPDATE products SET product_name='Think and Grow Rich', category='Books', unit_price=17349 WHERE product_id=50;
UPDATE products SET product_name='Dell Inspiron 15 2', category='Electronics', unit_price=17686 WHERE product_id=51;
UPDATE products SET product_name='HP Pavilion 14 2', category='Electronics', unit_price=18023 WHERE product_id=52;
UPDATE products SET product_name='Lenovo ThinkPad E14 2', category='Electronics', unit_price=18360 WHERE product_id=53;
UPDATE products SET product_name='Apple MacBook Air 2', category='Electronics', unit_price=18697 WHERE product_id=54;
UPDATE products SET product_name='Acer Aspire 7 2', category='Electronics', unit_price=19034 WHERE product_id=55;
UPDATE products SET product_name='Asus VivoBook 2', category='Electronics', unit_price=19371 WHERE product_id=56;
UPDATE products SET product_name='Samsung 24-inch Monitor 2', category='Electronics', unit_price=19708 WHERE product_id=57;
UPDATE products SET product_name='LG UltraWide Monitor 2', category='Electronics', unit_price=20045 WHERE product_id=58;
UPDATE products SET product_name='Logitech Wireless Mouse 2', category='Electronics', unit_price=20382 WHERE product_id=59;
UPDATE products SET product_name='HP Wireless Keyboard 2', category='Electronics', unit_price=20719 WHERE product_id=60;
UPDATE products SET product_name='Sony Bluetooth Speaker 2', category='Electronics', unit_price=21056 WHERE product_id=61;
UPDATE products SET product_name='JBL Flip Speaker 2', category='Electronics', unit_price=21393 WHERE product_id=62;
UPDATE products SET product_name='Canon EOS Camera 2', category='Electronics', unit_price=21730 WHERE product_id=63;
UPDATE products SET product_name='Nikon DSLR Camera 2', category='Electronics', unit_price=22067 WHERE product_id=64;
UPDATE products SET product_name='SanDisk SSD 2', category='Electronics', unit_price=22404 WHERE product_id=65;
UPDATE products SET product_name='WD External HDD 2', category='Electronics', unit_price=22741 WHERE product_id=66;
UPDATE products SET product_name='TP-Link Router 2', category='Electronics', unit_price=23078 WHERE product_id=67;
UPDATE products SET product_name='Mi Power Bank 2', category='Electronics', unit_price=23415 WHERE product_id=68;
UPDATE products SET product_name='Apple Magic Keyboard 2', category='Electronics', unit_price=23752 WHERE product_id=69;
UPDATE products SET product_name='Epson Printer 2', category='Electronics', unit_price=24089 WHERE product_id=70;
UPDATE products SET product_name='Office Chair 2', category='Furniture', unit_price=24426 WHERE product_id=71;
UPDATE products SET product_name='Study Desk 2', category='Furniture', unit_price=24763 WHERE product_id=72;
UPDATE products SET product_name='Bookshelf 2', category='Furniture', unit_price=25100 WHERE product_id=73;
UPDATE products SET product_name='Wooden Cabinet 2', category='Furniture', unit_price=25437 WHERE product_id=74;
UPDATE products SET product_name='Dining Table 2', category='Furniture', unit_price=25774 WHERE product_id=75;
UPDATE products SET product_name='Coffee Table 2', category='Furniture', unit_price=26111 WHERE product_id=76;
UPDATE products SET product_name='TV Unit 2', category='Furniture', unit_price=26448 WHERE product_id=77;
UPDATE products SET product_name='Wardrobe 2', category='Furniture', unit_price=26785 WHERE product_id=78;
UPDATE products SET product_name='Sofa Set 2', category='Furniture', unit_price=27122 WHERE product_id=79;
UPDATE products SET product_name='Bed Frame 2', category='Furniture', unit_price=27459 WHERE product_id=80;
UPDATE products SET product_name='Nike T-Shirt 2', category='Clothing', unit_price=27796 WHERE product_id=81;
UPDATE products SET product_name='Adidas Hoodie 2', category='Clothing', unit_price=28133 WHERE product_id=82;
UPDATE products SET product_name='Levis Jeans 2', category='Clothing', unit_price=28470 WHERE product_id=83;
UPDATE products SET product_name='Puma Shorts 2', category='Clothing', unit_price=28807 WHERE product_id=84;
UPDATE products SET product_name='Formal Shirt 2', category='Clothing', unit_price=29144 WHERE product_id=85;
UPDATE products SET product_name='Casual Shirt 2', category='Clothing', unit_price=29481 WHERE product_id=86;
UPDATE products SET product_name='Jacket 2', category='Clothing', unit_price=29818 WHERE product_id=87;
UPDATE products SET product_name='Sweatshirt 2', category='Clothing', unit_price=30155 WHERE product_id=88;
UPDATE products SET product_name='Track Pants 2', category='Clothing', unit_price=30492 WHERE product_id=89;
UPDATE products SET product_name='Kurti 2', category='Clothing', unit_price=30829 WHERE product_id=90;
UPDATE products SET product_name='Atomic Habits 2', category='Books', unit_price=31166 WHERE product_id=91;
UPDATE products SET product_name='The Alchemist 2', category='Books', unit_price=31503 WHERE product_id=92;
UPDATE products SET product_name='Rich Dad Poor Dad 2', category='Books', unit_price=31840 WHERE product_id=93;
UPDATE products SET product_name='Deep Work 2', category='Books', unit_price=32177 WHERE product_id=94;
UPDATE products SET product_name='Clean Code 2', category='Books', unit_price=32514 WHERE product_id=95;
UPDATE products SET product_name='Python Crash Course 2', category='Books', unit_price=32851 WHERE product_id=96;
UPDATE products SET product_name='Ikigai 2', category='Books', unit_price=33188 WHERE product_id=97;
UPDATE products SET product_name='Sapiens 2', category='Books', unit_price=33525 WHERE product_id=98;
UPDATE products SET product_name='Zero to One 2', category='Books', unit_price=33862 WHERE product_id=99;
UPDATE products SET product_name='Think and Grow Rich 2', category='Books', unit_price=34199 WHERE product_id=100;
UPDATE products SET product_name='Dell Inspiron 15 3', category='Electronics', unit_price=34536 WHERE product_id=101;
UPDATE products SET product_name='HP Pavilion 14 3', category='Electronics', unit_price=34873 WHERE product_id=102;
UPDATE products SET product_name='Lenovo ThinkPad E14 3', category='Electronics', unit_price=35210 WHERE product_id=103;
UPDATE products SET product_name='Apple MacBook Air 3', category='Electronics', unit_price=35547 WHERE product_id=104;
UPDATE products SET product_name='Acer Aspire 7 3', category='Electronics', unit_price=35884 WHERE product_id=105;
UPDATE products SET product_name='Asus VivoBook 3', category='Electronics', unit_price=36221 WHERE product_id=106;
UPDATE products SET product_name='Samsung 24-inch Monitor 3', category='Electronics', unit_price=36558 WHERE product_id=107;
UPDATE products SET product_name='LG UltraWide Monitor 3', category='Electronics', unit_price=36895 WHERE product_id=108;
UPDATE products SET product_name='Logitech Wireless Mouse 3', category='Electronics', unit_price=37232 WHERE product_id=109;
UPDATE products SET product_name='HP Wireless Keyboard 3', category='Electronics', unit_price=37569 WHERE product_id=110;
UPDATE products SET product_name='Sony Bluetooth Speaker 3', category='Electronics', unit_price=37906 WHERE product_id=111;
UPDATE products SET product_name='JBL Flip Speaker 3', category='Electronics', unit_price=38243 WHERE product_id=112;
UPDATE products SET product_name='Canon EOS Camera 3', category='Electronics', unit_price=38580 WHERE product_id=113;
UPDATE products SET product_name='Nikon DSLR Camera 3', category='Electronics', unit_price=38917 WHERE product_id=114;
UPDATE products SET product_name='SanDisk SSD 3', category='Electronics', unit_price=39254 WHERE product_id=115;
UPDATE products SET product_name='WD External HDD 3', category='Electronics', unit_price=39591 WHERE product_id=116;
UPDATE products SET product_name='TP-Link Router 3', category='Electronics', unit_price=39928 WHERE product_id=117;
UPDATE products SET product_name='Mi Power Bank 3', category='Electronics', unit_price=40265 WHERE product_id=118;
UPDATE products SET product_name='Apple Magic Keyboard 3', category='Electronics', unit_price=40602 WHERE product_id=119;
UPDATE products SET product_name='Epson Printer 3', category='Electronics', unit_price=40939 WHERE product_id=120;
UPDATE products SET product_name='Office Chair 3', category='Furniture', unit_price=41276 WHERE product_id=121;
UPDATE products SET product_name='Study Desk 3', category='Furniture', unit_price=41613 WHERE product_id=122;
UPDATE products SET product_name='Bookshelf 3', category='Furniture', unit_price=41950 WHERE product_id=123;
UPDATE products SET product_name='Wooden Cabinet 3', category='Furniture', unit_price=42287 WHERE product_id=124;
UPDATE products SET product_name='Dining Table 3', category='Furniture', unit_price=42624 WHERE product_id=125;
UPDATE products SET product_name='Coffee Table 3', category='Furniture', unit_price=42961 WHERE product_id=126;
UPDATE products SET product_name='TV Unit 3', category='Furniture', unit_price=43298 WHERE product_id=127;
UPDATE products SET product_name='Wardrobe 3', category='Furniture', unit_price=43635 WHERE product_id=128;
UPDATE products SET product_name='Sofa Set 3', category='Furniture', unit_price=43972 WHERE product_id=129;
UPDATE products SET product_name='Bed Frame 3', category='Furniture', unit_price=44309 WHERE product_id=130;
UPDATE products SET product_name='Nike T-Shirt 3', category='Clothing', unit_price=44646 WHERE product_id=131;
UPDATE products SET product_name='Adidas Hoodie 3', category='Clothing', unit_price=44983 WHERE product_id=132;
UPDATE products SET product_name='Levis Jeans 3', category='Clothing', unit_price=45320 WHERE product_id=133;
UPDATE products SET product_name='Puma Shorts 3', category='Clothing', unit_price=45657 WHERE product_id=134;
UPDATE products SET product_name='Formal Shirt 3', category='Clothing', unit_price=45994 WHERE product_id=135;
UPDATE products SET product_name='Casual Shirt 3', category='Clothing', unit_price=46331 WHERE product_id=136;
UPDATE products SET product_name='Jacket 3', category='Clothing', unit_price=46668 WHERE product_id=137;
UPDATE products SET product_name='Sweatshirt 3', category='Clothing', unit_price=47005 WHERE product_id=138;
UPDATE products SET product_name='Track Pants 3', category='Clothing', unit_price=47342 WHERE product_id=139;
UPDATE products SET product_name='Kurti 3', category='Clothing', unit_price=47679 WHERE product_id=140;
UPDATE products SET product_name='Atomic Habits 3', category='Books', unit_price=48016 WHERE product_id=141;
UPDATE products SET product_name='The Alchemist 3', category='Books', unit_price=48353 WHERE product_id=142;
UPDATE products SET product_name='Rich Dad Poor Dad 3', category='Books', unit_price=48690 WHERE product_id=143;
UPDATE products SET product_name='Deep Work 3', category='Books', unit_price=49027 WHERE product_id=144;
UPDATE products SET product_name='Clean Code 3', category='Books', unit_price=49364 WHERE product_id=145;
UPDATE products SET product_name='Python Crash Course 3', category='Books', unit_price=49701 WHERE product_id=146;
UPDATE products SET product_name='Ikigai 3', category='Books', unit_price=50038 WHERE product_id=147;
UPDATE products SET product_name='Sapiens 3', category='Books', unit_price=50375 WHERE product_id=148;
UPDATE products SET product_name='Zero to One 3', category='Books', unit_price=50712 WHERE product_id=149;
UPDATE products SET product_name='Think and Grow Rich 3', category='Books', unit_price=51049 WHERE product_id=150;
UPDATE products SET product_name='Dell Inspiron 15 4', category='Electronics', unit_price=51386 WHERE product_id=151;
UPDATE products SET product_name='HP Pavilion 14 4', category='Electronics', unit_price=51723 WHERE product_id=152;
UPDATE products SET product_name='Lenovo ThinkPad E14 4', category='Electronics', unit_price=52060 WHERE product_id=153;
UPDATE products SET product_name='Apple MacBook Air 4', category='Electronics', unit_price=52397 WHERE product_id=154;
UPDATE products SET product_name='Acer Aspire 7 4', category='Electronics', unit_price=52734 WHERE product_id=155;
UPDATE products SET product_name='Asus VivoBook 4', category='Electronics', unit_price=53071 WHERE product_id=156;
UPDATE products SET product_name='Samsung 24-inch Monitor 4', category='Electronics', unit_price=53408 WHERE product_id=157;
UPDATE products SET product_name='LG UltraWide Monitor 4', category='Electronics', unit_price=53745 WHERE product_id=158;
UPDATE products SET product_name='Logitech Wireless Mouse 4', category='Electronics', unit_price=54082 WHERE product_id=159;
UPDATE products SET product_name='HP Wireless Keyboard 4', category='Electronics', unit_price=54419 WHERE product_id=160;
UPDATE products SET product_name='Sony Bluetooth Speaker 4', category='Electronics', unit_price=54756 WHERE product_id=161;
UPDATE products SET product_name='JBL Flip Speaker 4', category='Electronics', unit_price=55093 WHERE product_id=162;
UPDATE products SET product_name='Canon EOS Camera 4', category='Electronics', unit_price=55430 WHERE product_id=163;
UPDATE products SET product_name='Nikon DSLR Camera 4', category='Electronics', unit_price=55767 WHERE product_id=164;
UPDATE products SET product_name='SanDisk SSD 4', category='Electronics', unit_price=56104 WHERE product_id=165;
UPDATE products SET product_name='WD External HDD 4', category='Electronics', unit_price=56441 WHERE product_id=166;
UPDATE products SET product_name='TP-Link Router 4', category='Electronics', unit_price=56778 WHERE product_id=167;
UPDATE products SET product_name='Mi Power Bank 4', category='Electronics', unit_price=57115 WHERE product_id=168;
UPDATE products SET product_name='Apple Magic Keyboard 4', category='Electronics', unit_price=57452 WHERE product_id=169;
UPDATE products SET product_name='Epson Printer 4', category='Electronics', unit_price=57789 WHERE product_id=170;
UPDATE products SET product_name='Office Chair 4', category='Furniture', unit_price=58126 WHERE product_id=171;
UPDATE products SET product_name='Study Desk 4', category='Furniture', unit_price=58463 WHERE product_id=172;
UPDATE products SET product_name='Bookshelf 4', category='Furniture', unit_price=58800 WHERE product_id=173;
UPDATE products SET product_name='Wooden Cabinet 4', category='Furniture', unit_price=59137 WHERE product_id=174;
UPDATE products SET product_name='Dining Table 4', category='Furniture', unit_price=59474 WHERE product_id=175;
UPDATE products SET product_name='Coffee Table 4', category='Furniture', unit_price=59811 WHERE product_id=176;
UPDATE products SET product_name='TV Unit 4', category='Furniture', unit_price=60148 WHERE product_id=177;
UPDATE products SET product_name='Wardrobe 4', category='Furniture', unit_price=60485 WHERE product_id=178;
UPDATE products SET product_name='Sofa Set 4', category='Furniture', unit_price=60822 WHERE product_id=179;
UPDATE products SET product_name='Bed Frame 4', category='Furniture', unit_price=61159 WHERE product_id=180;
UPDATE products SET product_name='Nike T-Shirt 4', category='Clothing', unit_price=61496 WHERE product_id=181;
UPDATE products SET product_name='Adidas Hoodie 4', category='Clothing', unit_price=61833 WHERE product_id=182;
UPDATE products SET product_name='Levis Jeans 4', category='Clothing', unit_price=62170 WHERE product_id=183;
UPDATE products SET product_name='Puma Shorts 4', category='Clothing', unit_price=62507 WHERE product_id=184;
UPDATE products SET product_name='Formal Shirt 4', category='Clothing', unit_price=62844 WHERE product_id=185;
UPDATE products SET product_name='Casual Shirt 4', category='Clothing', unit_price=63181 WHERE product_id=186;
UPDATE products SET product_name='Jacket 4', category='Clothing', unit_price=63518 WHERE product_id=187;
UPDATE products SET product_name='Sweatshirt 4', category='Clothing', unit_price=63855 WHERE product_id=188;
UPDATE products SET product_name='Track Pants 4', category='Clothing', unit_price=64192 WHERE product_id=189;
UPDATE products SET product_name='Kurti 4', category='Clothing', unit_price=64529 WHERE product_id=190;
UPDATE products SET product_name='Atomic Habits 4', category='Books', unit_price=64866 WHERE product_id=191;
UPDATE products SET product_name='The Alchemist 4', category='Books', unit_price=65203 WHERE product_id=192;
UPDATE products SET product_name='Rich Dad Poor Dad 4', category='Books', unit_price=65540 WHERE product_id=193;
UPDATE products SET product_name='Deep Work 4', category='Books', unit_price=65877 WHERE product_id=194;
UPDATE products SET product_name='Clean Code 4', category='Books', unit_price=66214 WHERE product_id=195;
UPDATE products SET product_name='Python Crash Course 4', category='Books', unit_price=66551 WHERE product_id=196;
UPDATE products SET product_name='Ikigai 4', category='Books', unit_price=66888 WHERE product_id=197;
UPDATE products SET product_name='Sapiens 4', category='Books', unit_price=67225 WHERE product_id=198;
UPDATE products SET product_name='Zero to One 4', category='Books', unit_price=67562 WHERE product_id=199;
UPDATE products SET product_name='Think and Grow Rich 4', category='Books', unit_price=67899 WHERE product_id=200;
UPDATE products SET product_name='Dell Inspiron 15 5', category='Electronics', unit_price=68236 WHERE product_id=201;
UPDATE products SET product_name='HP Pavilion 14 5', category='Electronics', unit_price=68573 WHERE product_id=202;
UPDATE products SET product_name='Lenovo ThinkPad E14 5', category='Electronics', unit_price=68910 WHERE product_id=203;
UPDATE products SET product_name='Apple MacBook Air 5', category='Electronics', unit_price=69247 WHERE product_id=204;
UPDATE products SET product_name='Acer Aspire 7 5', category='Electronics', unit_price=69584 WHERE product_id=205;
UPDATE products SET product_name='Asus VivoBook 5', category='Electronics', unit_price=69921 WHERE product_id=206;
UPDATE products SET product_name='Samsung 24-inch Monitor 5', category='Electronics', unit_price=70258 WHERE product_id=207;
UPDATE products SET product_name='LG UltraWide Monitor 5', category='Electronics', unit_price=70595 WHERE product_id=208;
UPDATE products SET product_name='Logitech Wireless Mouse 5', category='Electronics', unit_price=70932 WHERE product_id=209;
UPDATE products SET product_name='HP Wireless Keyboard 5', category='Electronics', unit_price=71269 WHERE product_id=210;
UPDATE products SET product_name='Sony Bluetooth Speaker 5', category='Electronics', unit_price=71606 WHERE product_id=211;
UPDATE products SET product_name='JBL Flip Speaker 5', category='Electronics', unit_price=71943 WHERE product_id=212;
UPDATE products SET product_name='Canon EOS Camera 5', category='Electronics', unit_price=72280 WHERE product_id=213;
UPDATE products SET product_name='Nikon DSLR Camera 5', category='Electronics', unit_price=72617 WHERE product_id=214;
UPDATE products SET product_name='SanDisk SSD 5', category='Electronics', unit_price=72954 WHERE product_id=215;
UPDATE products SET product_name='WD External HDD 5', category='Electronics', unit_price=73291 WHERE product_id=216;
UPDATE products SET product_name='TP-Link Router 5', category='Electronics', unit_price=73628 WHERE product_id=217;
UPDATE products SET product_name='Mi Power Bank 5', category='Electronics', unit_price=73965 WHERE product_id=218;
UPDATE products SET product_name='Apple Magic Keyboard 5', category='Electronics', unit_price=74302 WHERE product_id=219;
UPDATE products SET product_name='Epson Printer 5', category='Electronics', unit_price=74639 WHERE product_id=220;
UPDATE products SET product_name='Office Chair 5', category='Furniture', unit_price=74976 WHERE product_id=221;
UPDATE products SET product_name='Study Desk 5', category='Furniture', unit_price=75313 WHERE product_id=222;
UPDATE products SET product_name='Bookshelf 5', category='Furniture', unit_price=75650 WHERE product_id=223;
UPDATE products SET product_name='Wooden Cabinet 5', category='Furniture', unit_price=75987 WHERE product_id=224;
UPDATE products SET product_name='Dining Table 5', category='Furniture', unit_price=76324 WHERE product_id=225;
UPDATE products SET product_name='Coffee Table 5', category='Furniture', unit_price=76661 WHERE product_id=226;
UPDATE products SET product_name='TV Unit 5', category='Furniture', unit_price=76998 WHERE product_id=227;
UPDATE products SET product_name='Wardrobe 5', category='Furniture', unit_price=77335 WHERE product_id=228;
UPDATE products SET product_name='Sofa Set 5', category='Furniture', unit_price=77672 WHERE product_id=229;
UPDATE products SET product_name='Bed Frame 5', category='Furniture', unit_price=78009 WHERE product_id=230;
UPDATE products SET product_name='Nike T-Shirt 5', category='Clothing', unit_price=78346 WHERE product_id=231;
UPDATE products SET product_name='Adidas Hoodie 5', category='Clothing', unit_price=78683 WHERE product_id=232;
UPDATE products SET product_name='Levis Jeans 5', category='Clothing', unit_price=79020 WHERE product_id=233;
UPDATE products SET product_name='Puma Shorts 5', category='Clothing', unit_price=79357 WHERE product_id=234;
UPDATE products SET product_name='Formal Shirt 5', category='Clothing', unit_price=79694 WHERE product_id=235;
UPDATE products SET product_name='Casual Shirt 5', category='Clothing', unit_price=80031 WHERE product_id=236;
UPDATE products SET product_name='Jacket 5', category='Clothing', unit_price=80368 WHERE product_id=237;
UPDATE products SET product_name='Sweatshirt 5', category='Clothing', unit_price=80705 WHERE product_id=238;
UPDATE products SET product_name='Track Pants 5', category='Clothing', unit_price=81042 WHERE product_id=239;
UPDATE products SET product_name='Kurti 5', category='Clothing', unit_price=81379 WHERE product_id=240;
UPDATE products SET product_name='Atomic Habits 5', category='Books', unit_price=81716 WHERE product_id=241;
UPDATE products SET product_name='The Alchemist 5', category='Books', unit_price=82053 WHERE product_id=242;
UPDATE products SET product_name='Rich Dad Poor Dad 5', category='Books', unit_price=82390 WHERE product_id=243;
UPDATE products SET product_name='Deep Work 5', category='Books', unit_price=82727 WHERE product_id=244;
UPDATE products SET product_name='Clean Code 5', category='Books', unit_price=83064 WHERE product_id=245;
UPDATE products SET product_name='Python Crash Course 5', category='Books', unit_price=83401 WHERE product_id=246;
UPDATE products SET product_name='Ikigai 5', category='Books', unit_price=83738 WHERE product_id=247;
UPDATE products SET product_name='Sapiens 5', category='Books', unit_price=84075 WHERE product_id=248;
UPDATE products SET product_name='Zero to One 5', category='Books', unit_price=84412 WHERE product_id=249;
UPDATE products SET product_name='Think and Grow Rich 5', category='Books', unit_price=84749 WHERE product_id=250;
UPDATE products SET product_name='Dell Inspiron 15 6', category='Electronics', unit_price=85086 WHERE product_id=251;
UPDATE products SET product_name='HP Pavilion 14 6', category='Electronics', unit_price=85423 WHERE product_id=252;
UPDATE products SET product_name='Lenovo ThinkPad E14 6', category='Electronics', unit_price=85760 WHERE product_id=253;
UPDATE products SET product_name='Apple MacBook Air 6', category='Electronics', unit_price=86097 WHERE product_id=254;
UPDATE products SET product_name='Acer Aspire 7 6', category='Electronics', unit_price=86434 WHERE product_id=255;
UPDATE products SET product_name='Asus VivoBook 6', category='Electronics', unit_price=86771 WHERE product_id=256;
UPDATE products SET product_name='Samsung 24-inch Monitor 6', category='Electronics', unit_price=87108 WHERE product_id=257;
UPDATE products SET product_name='LG UltraWide Monitor 6', category='Electronics', unit_price=87445 WHERE product_id=258;
UPDATE products SET product_name='Logitech Wireless Mouse 6', category='Electronics', unit_price=87782 WHERE product_id=259;
UPDATE products SET product_name='HP Wireless Keyboard 6', category='Electronics', unit_price=88119 WHERE product_id=260;
UPDATE products SET product_name='Sony Bluetooth Speaker 6', category='Electronics', unit_price=88456 WHERE product_id=261;
UPDATE products SET product_name='JBL Flip Speaker 6', category='Electronics', unit_price=88793 WHERE product_id=262;
UPDATE products SET product_name='Canon EOS Camera 6', category='Electronics', unit_price=89130 WHERE product_id=263;
UPDATE products SET product_name='Nikon DSLR Camera 6', category='Electronics', unit_price=89467 WHERE product_id=264;
UPDATE products SET product_name='SanDisk SSD 6', category='Electronics', unit_price=89804 WHERE product_id=265;
UPDATE products SET product_name='WD External HDD 6', category='Electronics', unit_price=90141 WHERE product_id=266;
UPDATE products SET product_name='TP-Link Router 6', category='Electronics', unit_price=90478 WHERE product_id=267;
UPDATE products SET product_name='Mi Power Bank 6', category='Electronics', unit_price=815 WHERE product_id=268;
UPDATE products SET product_name='Apple Magic Keyboard 6', category='Electronics', unit_price=1152 WHERE product_id=269;
UPDATE products SET product_name='Epson Printer 6', category='Electronics', unit_price=1489 WHERE product_id=270;
UPDATE products SET product_name='Office Chair 6', category='Furniture', unit_price=1826 WHERE product_id=271;
UPDATE products SET product_name='Study Desk 6', category='Furniture', unit_price=2163 WHERE product_id=272;
UPDATE products SET product_name='Bookshelf 6', category='Furniture', unit_price=2500 WHERE product_id=273;
UPDATE products SET product_name='Wooden Cabinet 6', category='Furniture', unit_price=2837 WHERE product_id=274;
UPDATE products SET product_name='Dining Table 6', category='Furniture', unit_price=3174 WHERE product_id=275;
UPDATE products SET product_name='Coffee Table 6', category='Furniture', unit_price=3511 WHERE product_id=276;
UPDATE products SET product_name='TV Unit 6', category='Furniture', unit_price=3848 WHERE product_id=277;
UPDATE products SET product_name='Wardrobe 6', category='Furniture', unit_price=4185 WHERE product_id=278;
UPDATE products SET product_name='Sofa Set 6', category='Furniture', unit_price=4522 WHERE product_id=279;
UPDATE products SET product_name='Bed Frame 6', category='Furniture', unit_price=4859 WHERE product_id=280;
UPDATE products SET product_name='Nike T-Shirt 6', category='Clothing', unit_price=5196 WHERE product_id=281;
UPDATE products SET product_name='Adidas Hoodie 6', category='Clothing', unit_price=5533 WHERE product_id=282;
UPDATE products SET product_name='Levis Jeans 6', category='Clothing', unit_price=5870 WHERE product_id=283;
UPDATE products SET product_name='Puma Shorts 6', category='Clothing', unit_price=6207 WHERE product_id=284;
UPDATE products SET product_name='Formal Shirt 6', category='Clothing', unit_price=6544 WHERE product_id=285;
UPDATE products SET product_name='Casual Shirt 6', category='Clothing', unit_price=6881 WHERE product_id=286;
UPDATE products SET product_name='Jacket 6', category='Clothing', unit_price=7218 WHERE product_id=287;
UPDATE products SET product_name='Sweatshirt 6', category='Clothing', unit_price=7555 WHERE product_id=288;
UPDATE products SET product_name='Track Pants 6', category='Clothing', unit_price=7892 WHERE product_id=289;
UPDATE products SET product_name='Kurti 6', category='Clothing', unit_price=8229 WHERE product_id=290;
UPDATE products SET product_name='Atomic Habits 6', category='Books', unit_price=8566 WHERE product_id=291;
UPDATE products SET product_name='The Alchemist 6', category='Books', unit_price=8903 WHERE product_id=292;
UPDATE products SET product_name='Rich Dad Poor Dad 6', category='Books', unit_price=9240 WHERE product_id=293;
UPDATE products SET product_name='Deep Work 6', category='Books', unit_price=9577 WHERE product_id=294;
UPDATE products SET product_name='Clean Code 6', category='Books', unit_price=9914 WHERE product_id=295;
UPDATE products SET product_name='Python Crash Course 6', category='Books', unit_price=10251 WHERE product_id=296;
UPDATE products SET product_name='Ikigai 6', category='Books', unit_price=10588 WHERE product_id=297;
UPDATE products SET product_name='Sapiens 6', category='Books', unit_price=10925 WHERE product_id=298;
UPDATE products SET product_name='Zero to One 6', category='Books', unit_price=11262 WHERE product_id=299;
UPDATE products SET product_name='Think and Grow Rich 6', category='Books', unit_price=11599 WHERE product_id=300;